server:
  port: 8001

#mybatisÓ³ÉäÎÄ¼ş
mybatis:
  mapper-locations: classpath*:mapper/*.xml

spring:
  profiles:
    active: dev
  redis:
    database: ${REDIS_DB:0}
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 5000
